export const countries = [
  "Afghanistan",
  "Åland Islands",
  "Albania",
  "Algeria",
  "American Samoa",
  "Andorra",
  "Angola",
  "Anguilla",
  "Antarctica",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Aruba",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bermuda",
  "Bhutan",
  "Bolivia",
  "Bosnia and Herzegovina",
  "Botswana",
  "Bouvet Island",
  "Brazil",
  "British Indian Ocean Territory",
  "Brunei Darussalam",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Cape Verde",
  "Cayman Islands",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Christmas Island",
  "Cocos (Keeling) Islands",
  "Colombia",
  "Comoros",
  "Congo",
  "Congo, The Democratic Republic of The",
  "Cook Islands",
  "Costa Rica",
  "Cote D'ivoire",
  "Croatia",
  "Cuba",
  "Cyprus",
  "Czech Republic",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Ethiopia",
  "Falkland Islands (Malvinas)",
  "Faroe Islands",
  "Fiji",
  "Finland",
  "France",
  "French Guiana",
  "French Polynesia",
  "French Southern Territories",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Gibraltar",
  "Greece",
  "Greenland",
  "Grenada",
  "Guadeloupe",
  "Guam",
  "Guatemala",
  "Guernsey",
  "Guinea",
  "Guinea-bissau",
  "Guyana",
  "Haiti",
  "Heard Island and Mcdonald Islands",
  "Holy See (Vatican City State)",
  "Honduras",
  "Hong Kong",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran, Islamic Republic of",
  "Iraq",
  "Ireland",
  "Isle of Man",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jersey",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Korea",
  "Democratic People's Republic of Korea",
  "Republic of Kuwait",
  "Kyrgyzstan",
  "Lao People's Democratic Republic",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libyan Arab Jamahiriya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Macao",
  "Macedonia, The Former Yugoslav Republic of",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Martinique",
  "Mauritania",
  "Mauritius",
  "Mayotte",
  "Mexico",
  "Micronesia, Federated States of",
  "Moldova, Republic of",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Montserrat",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "Netherlands Antilles",
  "New Caledonia",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "Niue",
  "Norfolk Island",
  "Northern Mariana Islands",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestinian Territory, Occupied",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Pitcairn",
  "Poland",
  "Portugal",
  "Puerto Rico",
  "Qatar",
  "Reunion",
  "Romania",
  "Russian Federation",
  "Rwanda",
  "Saint Helena",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Pierre and Miquelon",
  "Saint Vincent and The Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Georgia and The South Sandwich Islands",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Svalbard and Jan Mayen",
  "Swaziland",
  "Sweden",
  "Switzerland",
  "Syrian Arab Republic",
  "Taiwan (ROC)",
  "Tajikistan",
  "Tanzania, United Republic of",
  "Thailand",
  "Timor-leste",
  "Togo",
  "Tokelau",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Turks and Caicos Islands",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "United States Minor Outlying Islands",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Venezuela",
  "Viet Nam",
  "Virgin Islands, British",
  "Virgin Islands, U.S.",
  "Wallis and Futuna",
  "Western Sahara",
  "Yemen",
  "Zambia",
  "Zimbabwe",
];

export const languages = [
  "Afar",
  "Abkhazian",
  "Achinese",
  "Acoli",
  "Adangme",
  "Adyghe Adygei",
  "Afro-Asiatic languages",
  "Afrihili",
  "Afrikaans",
  "Ainu",
  "Akan",
  "Akkadian",
  "Albanian",
  "Aleut",
  "Algonquian languages",
  "Southern Altai",
  "Amharic",
  "English",
  "Angika",
  "Apache languages",
  "Arabic",
  "Official Aramaic (700-300 BCE) Imperial Aramaic (700-300 BCE)",
  "Aragonese",
  "Armenian",
  "Mapudungun Mapuche",
  "Arapaho",
  "Artificial languages",
  "Arawak",
  "Assamese",
  "Asturian Bable Leonese Asturleonese",
  "Athapascan languages",
  "Australian languages",
  "Avaric",
  "Avestan",
  "Awadhi",
  "Aymara",
  "Azerbaijani",
  "Banda languages",
  "Bamileke languages",
  "Bashkir",
  "Baluchi",
  "Bambara",
  "Balinese",
  "Basque",
  "Basa",
  "Baltic languages",
  "Beja Bedawiyet",
  "Belarusian",
  "Bemba",
  "Bengali",
  "Berber languages",
  "Bhojpuri",
  "Bihari languages",
  "Bikol",
  "Bini Edo",
  "Bislama",
  "Siksika",
  "Bantu (Other)",
  "Bosnian",
  "Braj",
  "Breton",
  "Batak languages",
  "Buriat",
  "Buginese",
  "Bulgarian",
  "Burmese",
  "Blin Bilin",
  "Caddo",
  "Central American Indian languages",
  "Galibi Carib",
  "Catalan Valencian",
  "Caucasian languages",
  "Cebuano",
  "Celtic languages",
  "Chamorro",
  "Chibcha",
  "Chechen",
  "Chagatai",
  "Chinese",
  "Chuukese",
  "Mari",
  "Chinook jargon",
  "Choctaw",
  "Chipewyan Dene Suline",
  "Cherokee",
  "Church Slavic Old Slavonic Church Slavonic Old Bulgarian Old Church Slavonic",
  "Chuvash",
  "Cheyenne",
  "Chamic languages",
  "Coptic",
  "Cornish",
  "Corsican",
  "Creoles and pidgins",
  "Creoles and pidgins",
  "Creoles and pidgins",
  "Cree",
  "Crimean Tatar Crimean Turkish",
  "Creoles and pidgins ",
  "Kashubian",
  "Cushitic languages",
  "Czech",
  "Dakota",
  "Danish",
  "Dargwa",
  "Land Dayak languages",
  "Delaware",
  "Slave (Athapascan)",
  "Dogrib",
  "Dinka",
  "Divehi Dhivehi Maldivian",
  "Dogri",
  "Dravidian languages",
  "Lower Sorbian",
  "Duala",
  "Dutch",
  "Dutch Flemish",
  "Dyula",
  "Dzongkha",
  "Efik",
  "Egyptian (Ancient)",
  "Ekajuk",
  "Elamite",
  "English",
  "English",
  "Esperanto",
  "Estonian",
  "Ewe",
  "Ewondo",
  "Fang",
  "Faroese",
  "Fanti",
  "Fijian",
  "Filipino Pilipino",
  "Finnish",
  "Finno-Ugrian languages",
  "Fon",
  "French",
  "French",
  "French",
  "Northern Frisian",
  "Eastern Frisian",
  "Western Frisian",
  "Fulah",
  "Friulian",
  "Ga",
  "Gayo",
  "Gbaya",
  "Germanic languages",
  "Georgian",
  "German",
  "Geez",
  "Gilbertese",
  "Gaelic Scottish Gaelic",
  "Irish",
  "Galician",
  "Manx",
  "German",
  "German",
  "Gondi",
  "Gorontalo",
  "Gothic",
  "Grebo",
  "Greek",
  "Greek",
  "Guarani",
  "Swiss German Alemannic Alsatian",
  "Gujarati",
  "Gwich'in",
  "Haida",
  "Haitian Haitian Creole",
  "Hausa",
  "Hawaiian",
  "Hebrew",
  "Herero",
  "Hiligaynon",
  "Himachali languages Western Pahari languages",
  "Hindi",
  "Hittite",
  "Hmong Mong",
  "Hiri Motu",
  "Croatian",
  "Upper Sorbian",
  "Hungarian",
  "Hupa",
  "Iban",
  "Igbo",
  "Icelandic",
  "Ido",
  "Sichuan Yi Nuosu",
  "Ijo languages",
  "Inuktitut",
  "Interlingue Occidental",
  "Iloko",
  "Interlingua (International Auxiliary Language Association)",
  "Indic languages",
  "Indonesian",
  "Indo-European languages",
  "Ingush",
  "Inupiaq",
  "Iranian languages",
  "Iroquoian languages",
  "Italian",
  "Javanese",
  "Lojban",
  "Japanese",
  "Judeo-Persian",
  "Judeo-Arabic",
  "Kara-Kalpak",
  "Kabyle",
  "Kachin Jingpho",
  "Kalaallisut Greenlandic",
  "Kamba",
  "Kannada",
  "Karen languages",
  "Kashmiri",
  "Kanuri",
  "Kawi",
  "Kazakh",
  "Kabardian",
  "Khasi",
  "Khoisan languages",
  "Central Khmer",
  "Khotanese Sakan",
  "Kikuyu Gikuyu",
  "Kinyarwanda",
  "Kirghiz Kyrgyz",
  "Kimbundu",
  "Konkani",
  "Komi",
  "Kongo",
  "Korean",
  "Kosraean",
  "Kpelle",
  "Karachay-Balkar",
  "Karelian",
  "Kru languages",
  "Kurukh",
  "Kuanyama Kwanyama",
  "Kumyk",
  "Kurdish",
  "Kutenai",
  "Ladino",
  "Lahnda",
  "Lamba",
  "Lao",
  "Latin",
  "Latvian",
  "Lezghian",
  "Limburgan Limburger Limburgish",
  "Lingala",
  "Lithuanian",
  "Mongo",
  "Lozi",
  "Luxembourgish Letzeburgesch",
  "Luba-Lulua",
  "Luba-Katanga",
  "Ganda",
  "Luiseno",
  "Lunda",
  "Luo (Kenya and Tanzania)",
  "Lushai",
  "Macedonian",
  "Madurese",
  "Magahi",
  "Marshallese",
  "Maithili",
  "Makasar",
  "Malayalam",
  "Mandingo",
  "Maori",
  "Austronesian languages",
  "Marathi",
  "Masai",
  "Malay",
  "Moksha",
  "Mandar",
  "Mende",
  "Irish",
  "Mi'kmaq Micmac",
  "Minangkabau",
  "Uncoded languages",
  "Mon-Khmer languages",
  "Malagasy",
  "Maltese",
  "Manchu",
  "Manipuri",
  "Manobo languages",
  "Mohawk",
  "Mongolian",
  "Mossi",
  "Multiple languages",
  "Munda languages",
  "Creek",
  "Mirandese",
  "Marwari",
  "Mayan languages",
  "Erzya",
  "Nahuatl languages",
  "North American Indian languages",
  "Neapolitan",
  "Nauru",
  "Navajo Navaho",
  "Ndebele",
  "Ndebele",
  "Ndonga",
  "Low German Low Saxon German",
  "Nepali",
  "Nepal Bhasa Newari",
  "Nias",
  "Niger-Kordofanian languages",
  "Niuean",
  "Norwegian Nynorsk Nynorsk",
  "Bokmål",
  "Nogai",
  "Norse",
  "Norwegian",
  "N'Ko",
  "Pedi Sepedi Northern Sotho",
  "Nubian languages",
  "Classical Newari Old Newari Classical Nepal Bhasa",
  "Chichewa Chewa Nyanja",
  "Nyamwezi",
  "Nyankole",
  "Nyoro",
  "Nzima",
  "Occitan (post 1500) Provençal",
  "Ojibwa",
  "Oriya",
  "Oromo",
  "Osage",
  "Ossetian Ossetic",
  "Turkish",
  "Otomian languages",
  "Papuan languages",
  "Pangasinan",
  "Pahlavi",
  "Pampanga Kapampangan",
  "Panjabi Punjabi",
  "Papiamento",
  "Palauan",
  "Persian",
  "Persian",
  "Philippine languages",
  "Phoenician",
  "Pali",
  "Polish",
  "Pohnpeian",
  "Portuguese",
  "Prakrit languages",
  "Provençal",
  "Pushto Pashto",
  "Quechua",
  "Rajasthani",
  "Rapanui",
  "Rarotongan Cook Islands Maori",
  "Romance languages",
  "Romansh",
  "Romany",
  "Romanian Moldavian Moldovan",
  "Rundi",
  "Aromanian Arumanian Macedo-Romanian",
  "Russian",
  "Sandawe",
  "Sango",
  "Yakut",
  "South American Indian (Other)",
  "Salishan languages",
  "Samaritan Aramaic",
  "Sanskrit",
  "Sasak",
  "Santali",
  "Sicilian",
  "Scots",
  "Selkup",
  "Semitic languages",
  "Irish",
  "Sign Languages",
  "Shan",
  "Sidamo",
  "Sinhala Sinhalese",
  "Siouan languages",
  "Sino-Tibetan languages",
  "Slavic languages",
  "Slovak",
  "Slovenian",
  "Southern Sami",
  "Northern Sami",
  "Sami languages",
  "Lule Sami",
  "Inari Sami",
  "Samoan",
  "Skolt Sami",
  "Shona",
  "Sindhi",
  "Soninke",
  "Sogdian",
  "Somali",
  "Songhai languages",
  "Sotho",
  "Spanish Castilian",
  "Sardinian",
  "Sranan Tongo",
  "Serbian",
  "Serer",
  "Nilo-Saharan languages",
  "Swati",
  "Sukuma",
  "Sundanese",
  "Susu",
  "Sumerian",
  "Swahili",
  "Swedish",
  "Classical Syriac",
  "Syriac",
  "Tahitian",
  "Tai languages",
  "Tamil",
  "Tatar",
  "Telugu",
  "Timne",
  "Tereno",
  "Tetum",
  "Tajik",
  "Tagalog",
  "Thai",
  "Tibetan",
  "Tigre",
  "Tigrinya",
  "Tiv",
  "Tokelau",
  "Klingon tlhIngan-Hol",
  "Tlingit",
  "Tamashek",
  "Tonga (Nyasa)",
  "Tonga (Tonga Islands)",
  "Tok Pisin",
  "Tsimshian",
  "Tswana",
  "Tsonga",
  "Turkmen",
  "Tumbuka",
  "Tupi languages",
  "Turkish",
  "Altaic languages",
  "Tuvalu",
  "Twi",
  "Tuvinian",
  "Udmurt",
  "Ugaritic",
  "Uighur Uyghur",
  "Ukrainian",
  "Umbundu",
  "Undetermined",
  "Urdu",
  "Uzbek",
  "Vai",
  "Venda",
  "Vietnamese",
  "Volapük",
  "Votic",
  "Wakashan languages",
  "Walamo",
  "Waray",
  "Washo",
  "Welsh",
  "Sorbian languages",
  "Walloon",
  "Wolof",
  "Kalmyk Oirat",
  "Xhosa",
  "Yao",
  "Yapese",
  "Yiddish",
  "Yoruba",
  "Yupik languages",
  "Zapotec",
  "Blissymbols Blissymbolics Bliss",
  "Zenaga",
  "Zhuang Chuang",
  "Zande languages",
  "Zulu",
  "Zuni",
  "No linguistic content Not applicable",
  "Zaza Dimili Dimli Kirdki Kirmanjki Zazaki",
];

export const nationalities = [
  "Prefer not to say",
  "Afghan",
  "Albanian",
  "Algerian",
  "American",
  "Andorran",
  "Angolan",
  "Antiguans",
  "Argentinean",
  "Armenian",
  "Australian",
  "Austrian",
  "Azerbaijani",
  "Bahamian",
  "Bahraini",
  "Bangladeshi",
  "Barbadian",
  "Barbudans",
  "Batswana",
  "Belarusian",
  "Belgian",
  "Belizean",
  "Beninese",
  "Bhutanese",
  "Bolivian",
  "Bosnian",
  "Brazilian",
  "British",
  "Bruneian",
  "Bulgarian",
  "Burkinabe",
  "Burmese",
  "Burundian",
  "Cambodian",
  "Cameroonian",
  "Canadian",
  "Cape Verdean",
  "Central African",
  "Chadian",
  "Chilean",
  "Chinese",
  "Colombian",
  "Comoran",
  "Congolese",
  "Costa Rican",
  "Croatian",
  "Cuban",
  "Cypriot",
  "Czech",
  "Danish",
  "Djibouti",
  "Dominican",
  "Dutch",
  "East Timorese",
  "Ecuadorean",
  "Egyptian",
  "Emirian",
  "Equatorial Guinean",
  "Eritrean",
  "Estonian",
  "Ethiopian",
  "Fijian",
  "Filipino",
  "Finnish",
  "French",
  "Gabonese",
  "Gambian",
  "Georgian",
  "German",
  "Ghanaian",
  "Greek",
  "Grenadian",
  "Guatemalan",
  "Guinea-Bissauan",
  "Guinean",
  "Guyanese",
  "Haitian",
  "Herzegovinian",
  "Honduran",
  "Hungarian",
  "I-Kiribati",
  "Icelander",
  "Indian",
  "Indonesian",
  "Iranian",
  "Iraqi",
  "Irish",
  "Israeli",
  "Italian",
  "Ivorian",
  "Jamaican",
  "Japanese",
  "Jordanian",
  "Kazakhstani",
  "Kenyan",
  "Kittian and Nevisian",
  "Kuwaiti",
  "Kyrgyz",
  "Laotian",
  "Latvian",
  "Lebanese",
  "Liberian",
  "Libyan",
  "Liechtensteiner",
  "Lithuanian",
  "Luxembourger",
  "Macedonian",
  "Malagasy",
  "Malawian",
  "Malaysian",
  "Maldivian",
  "Malian",
  "Maltese",
  "Marshallese",
  "Mauritanian",
  "Mauritian",
  "Mexican",
  "Micronesian",
  "Moldovan",
  "Monacan",
  "Mongolian",
  "Moroccan",
  "Mosotho",
  "Motswana",
  "Mozambican",
  "Namibian",
  "Nauruan",
  "Nepalese",
  "New Zealander",
  "Ni-Vanuatu",
  "Nicaraguan",
  "Nigerian",
  "Nigerien",
  "North Korean",
  "Northern Irish",
  "Norwegian",
  "Omani",
  "Pakistani",
  "Palauan",
  "Panamanian",
  "Papua New Guinean",
  "Paraguayan",
  "Peruvian",
  "Polish",
  "Portuguese",
  "Qatari",
  "Romanian",
  "Russian",
  "Rwandan",
  "Saint Lucian",
  "Salvadoran",
  "Samoan",
  "San Marinese",
  "Sao Tomean",
  "Saudi",
  "Scottish",
  "Senegalese",
  "Serbian",
  "Seychellois",
  "Sierra Leonean",
  "Singaporean",
  "Slovakian",
  "Slovenian",
  "Solomon Islander",
  "Somali",
  "South African",
  "South Korean",
  "Spanish",
  "Sri Lankan",
  "Sudanese",
  "Surinamer",
  "Swazi",
  "Swedish",
  "Swiss",
  "Syrian",
  "Taiwanese",
  "Tajik",
  "Tanzanian",
  "Thai",
  "Togolese",
  "Tongan",
  "Trinidadian or Tobagonian",
  "Tunisian",
  "Turkish",
  "Tuvaluan",
  "Ugandan",
  "Ukrainian",
  "Uruguayan",
  "Uzbekistani",
  "Venezuelan",
  "Vietnamese",
  "Welsh",
  "Yemenite",
  "Zambian",
  "Zimbabwean",
];

export const timeZones = [
  "(GMT -12:00) Eniwetok, Kwajalein",
  "(GMT -11:00) Midway Island, Samoa",
  "(GMT -10:00) Hawaii",
  "(GMT -9:30) Taiohae",
  "(GMT -9:00) Alaska",
  "(GMT -8:00) Pacific Time (US & Canada)",
  "(GMT -7:00) Mountain Time (US & Canada)",
  "(GMT -6:00) Central Time (US & Canada), Mexico City",
  "(GMT -5:00) Eastern Time (US & Canada), Bogota, Lima",
  "(GMT -4:30) Caracas",
  "(GMT -4:00) Atlantic Time (Canada), Caracas, La Paz",
  "(GMT -3:30) Newfoundland",
  "(GMT -3:00) Brazil, Buenos Aires, Georgetown",
  "(GMT -2:00) Mid-Atlantic",
  "(GMT -1:00) Azores, Cape Verde Islands",
  "(GMT) Western Europe Time, London, Lisbon, Casablanca",
  "(GMT +1:00) Brussels, Copenhagen, Madrid, Paris",
  "(GMT +2:00) Kaliningrad, South Africa",
  "(GMT +3:00) Baghdad, Riyadh, Moscow, St. Petersburg",
  "(GMT +3:30) Tehran",
  "(GMT +4:00) Abu Dhabi, Muscat, Baku, Tbilisi",
  "(GMT +4:30) Kabul",
  "(GMT +5:00) Ekaterinburg, Islamabad, Karachi, Tashkent",
  "(GMT +5:30) Bombay, Calcutta, Madras, New Delhi",
  "(GMT +5:45) Kathmandu, Pokhara",
  "(GMT +6:00) Almaty, Dhaka, Colombo",
  "(GMT +6:30) Yangon, Mandalay",
  "(GMT +7:00) Bangkok, Hanoi, Jakarta",
  "(GMT +8:00) Beijing, Perth, Singapore, Hong Kong",
  "(GMT +8:45) Eucla",
  "(GMT +9:00) Tokyo, Seoul, Osaka, Sapporo, Yakutsk",
  "(GMT +9:30) Adelaide, Darwin",
  "(GMT +10:00) Eastern Australia, Guam, Vladivostok",
  "(GMT +10:30) Lord Howe Island",
  "(GMT +11:00) Magadan, Solomon Islands, New Caledonia",
  "(GMT +11:30) Norfolk Island",
  "(GMT +12:00) Auckland, Wellington, Fiji, Kamchatka",
  "(GMT +12:45) Chatham Islands",
  "(GMT +13:00) Apia, Nukualofa",
  "(GMT +14:00) Line Islands, Tokelau",
];
