const JobsData = [
  {
    id: 1,
    logo: "images/logo.svg",
    jobTitle: "UI/UX Designer",
    company_name: "Nets-International",
    jobStatus: "Full Time",
    location: "Islamabad, PK(On-site)",
    applicant: "20",
    date: "22/03/2022",
    salary: 95000,
  },
  {
    id: 2,
    logo: "../images/netflix.svg",
    jobTitle: "UI/UX Designer",
    company_name: "Nets-International",
    jobStatus: "Part Time",
    location: "Islamabad, PK(On-site)",
    applicant: "20",
    date: "22/03/2022",
    salary: 65000,
  },
  {
    id: 3,
    logo: "../images/macd.svg",
    jobTitle: "UI/UX Designer",
    company_name: "Nets-International",
    jobStatus: "Full Time",
    location: "Islamabad, PK(On-site)",
    applicant: "20",
    date: "22/03/2022",
    salary: 65000,
  },
  {
    id: 4,
    logo: "../images/dell.svg",
    jobTitle: "UI/UX Designer",
    company_name: "Nets-International",
    jobStatus: "Full Time",
    location: "Islamabad, PK(On-site)",
    applicant: "20",
    date: "22/03/2022",
    salary: 65000,
  },
  {
    id: 5,
    logo: "../images/logo.svg",
    jobTitle: "UI/UX Designer",
    company_name: "Nets-International",
    jobStatus: "Full Time",
    location: "Islamabad, PK(On-site)",
    applicant: "20",
    date: "22/03/2022",
    salary: 65000,
  },
  {
    id: 6,
    logo: "../images/logo.svg",
    jobTitle: "UI/UX Designer",
    company_name: "Nets-International",
    jobStatus: "Full Time",
    location: "Islamabad, PK(On-site)",
    applicant: "20",
    date: "22/03/2022",
    salary: 65000,
  },
  {
    id: 7,
    logo: "../images/logo.svg",
    jobTitle: "UI/UX Designer",
    company_name: "Nets-International",
    jobStatus: "Full Time",
    location: "Islamabad, PK(On-site)",
    applicant: "20",
    date: "22/03/2022",
    salary: 65000,
  },
];
export default JobsData;
