const MyData = [
  {
    id: 1,
    image: "../images/myprofile.svg",
    name: "Raza Raheem",
    post: "UI/UX Designer",
    company_name: "Nets-International",
    location: "pakistan",
    setting: "../images/dots.svg",
  },
  {
    id: 2,
    image: "../images/dell.svg",
    name: "UI/UX Designer",
    post: "Nets-International",
    company_name: "Nets-International",
    location: "pakistan",
    setting: "../images/dots.svg",
  },
  {
    id: 3,
    image: "../images/dell.svg",
    name: "UI/UX Designer",
    post: "Nets-International",
    company_name: "Nets-International",
    location: "pakistan",
    setting: "../images/dots.svg",
  },
  {
    id: 4,
    image: "../images/dell.svg",
    name: "UI/UX Designer",
    post: "Nets-International",
    company_name: "Nets-International",
    location: "pakistan",
    setting: "../images/dots.svg",
  },
  {
    id: 5,
    image: "../images/dell.svg",
    name: "UI/UX Designer",
    post: "Nets-International",
    company_name: "Nets-International",
    location: "pakistan",
    setting: "../images/dots.svg",
  },
  {
    id: 6,
    image: "../images/dell.svg",
    name: "UI/UX Designer",
    post: "Nets-International",
    company_name: "Nets-International",
    location: "pakistan",
    setting: "../images/dots.svg",
  },
];
export default MyData;
